Agrobot1/Agrobot1/Models/ErrorViewModel.cs
namespace Agrobot1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Agrobot1/Agrobot1/Models/parte.cs
namespace Agrobot1.Models
{
    public class parte
    {
        public int id { get; set; }
    }
}

Agrobot1/Agrobot1/Controllers/HomeController.cs
using Agrobot1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Agrobot1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Agrobot1/Agrobot1/Controllers/partesController.cs
using Agrobot1.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Agrobot1.Models
{
    public class partesController : Controller
    {
        private readonly Agrobot1Context _context;

        public partesController(Agrobot1Context context)
        {
            _context = context;
        }

        // GET: partes
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // GET: partes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parte = await _context.parte
                .FirstOrDefaultAsync(m => m.id == id);
            if (parte == null)
            {
                return NotFound();
            }

            return View(parte);
        }

        // GET: partes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: partes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id")] parte parte)
        {
            if (ModelState.IsValid)
            {
                _context.Add(parte);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(parte);
        }

        // GET: partes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parte = await _context.parte.FindAsync(id);
            if (parte == null)
            {
                return NotFound();
            }
            return View(parte);
        }

        // POST: partes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id")] parte parte)
        {
            if (id != parte.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parte);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!parteExists(parte.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parte);
        }

        // GET: partes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parte = await _context.parte
                .FirstOrDefaultAsync(m => m.id == id);
            if (parte == null)
            {
                return NotFound();
            }

            return View(parte);
        }

        // POST: partes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var parte = await _context.parte.FindAsync(id);
            _context.parte.Remove(parte);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool parteExists(int id)
        {
            return _context.parte.Any(e => e.id == id);
        }
    }
}

Agrobot1/Agrobot1/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Agrobot en sus cultivos"; }

<div class="text-center">
    <h1 class="display-4">Agrobot "Robot Fertilizador"</h1>
</div>
<h2>¿QUE ES AGROBOT?</h2>
<p>
    El Proyecto AGROBOT, es un robot autónomo que fertiliza campos de cultivo,haciéndolo a la vez que transita entre los cultivos.
    Para fertilizar los campos usa el método de fertilización radicular localizado (aplicación directa al suelo en zonas específicas),
    haciendo uso de soluciones fertilizantes. Agrobot será un robot destinado a fertilizar campos de monocultivo,
    el cual se desplazará haciendo uso de un mapa virtual realizado con el sobrevuelo de un dron para escanear el terreno.
</p>
<h1>¿COMO SE HISO?</h1>

<p>Agrobot se creo usando el software de simulacion WetBots y el software visual studio, para la implementacion de la simulacion</p>
<img src="~/Img/visual_studio_2015.jpg" width="300" height="300" />
<img src="~/Img/webots.jpg" width="300" height="300" />
<p>
    En un principio se realizo una pequeña investigacion, para conocer si ya existian proyectos parecidos y tambiem
    para saber como recrear un modelo eficiente para la distribucion y almacenamiento de fertilizante.
</p>
<img src="~/Img/agro logo.jpg" id="logo" width="900" height="300" />

Agrobot1/Agrobot1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agrobot1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Agrobot</a>
                        </li>
                        <!--<li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="partes" asp-action="Index">¿Que es?</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">¿Como se hizo?</a>
    </li>-->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Agrobot - Robot Fertilizante
        </div>
    </footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Agrobot1/Agrobot1/Views/partes/Create.cshtml
@model Agrobot1.Models.parte

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>parte</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agrobot1/Agrobot1/Views/partes/Delete.cshtml
@model Agrobot1.Models.parte

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>parte</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Agrobot1/Agrobot1/Views/partes/Details.cshtml
@model Agrobot1.Models.parte

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>parte</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Agrobot1/Agrobot1/Views/partes/Edit.cshtml
@model Agrobot1.Models.parte

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>parte</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agrobot1/Agrobot1/Views/partes/Index.cshtml
@model IEnumerable<Agrobot1.Models.parte>

@{
    ViewData["Title"] = "Que es agrobot";
}

<h1>¿QUE ES AGROBOT?</h1>
<p>
El Proyecto AGROBOT, es un robot autónomo que fertiliza campos de cultivo,haciéndolo a la vez que transita entre los cultivos.
Para fertilizar los campos usa el método de fertilización radicular localizado (aplicación directa al suelo en zonas específicas),
haciendo uso de soluciones fertilizantes. Agrobot será un robot destinado a fertilizar campos de monocultivo,
el cual se desplazará haciendo uso de un mapa virtual realizado con el sobrevuelo de un dron para escanear el terreno.
</p>